galaxy_url: http://your/galaxy/url
galaxy_api_key: your_galaxy_api_key
galaxy_config: /opt/source/galaxy/web/universe_wsgi.ini
program:
  bowtie: bowtie
  samtools: samtools
  bwa: bwa
  maq: maq
  ucsc_bigwig: wigToBigWig
  picard: /source/Picard
  fastx_stats: fastx_quality_stats
  fastx_graph: fastq_quality_boxplot_graph.sh
  pdflatex: pdflatex
  ps2pdf: ps2pdf
  solexaqa: SolexaQA.pl
algorithm:
  aligner: bowtie
  max_errors: 2
  num_cores: 8
  stringency: high
  quality_format: Illumina
  platform: SOLEXA
  recalibrate: false
  snpcall: false

msg_process_tag: sqn_finished_process
local_sqn_dir: /store4/solexadata

msg_store_tag: sqn_finished_store
store_dir: /mad/store/clients/cscshared/solexadata
store_user: cscshared
store_host: bricklayer01.partners.org

analysis:
  base_dir: /array0/projects/Sequencing
  towig_script: bam_to_wiggle.py
  process_program: automated_initial_analysis.py
  upload_program: upload_to_galaxy.py
# configuration algorithm changes for custom post-processing steps
custom_algorithms:
  'Broad SNP':
    ref_ext: '-broad'
    aligner: maq
    recalibrate: true
    snpcall: true
    dbsnp: snps/snp130.vcf
    hybrid_bait: bait_list
    hybrid_target: target_list
  'SNP calling':
    aligner: bwa
    recalibrate: true
    snpcall: true
    dbsnp: snps/snp130.vcf
