msg_process_tag: sqn_finished_process
msg_store_tag: sqn_finished_store
dump_directories:
  - /array10
  - /array11
  - /array12
# Pointer to a plain text file which will be used to keep track of 
# directories that have already been transferred.
msg_db: /home/chapman/transfer/transferred.db
