msg_process_tag: sqn_finished_process
msg_store_tag: sqn_finished_store
dump_directories:
  - /home/hiseq.hiseq/illumina
# Pointer to a plain text file which will be used to keep track of
# directories that have already been transferred.
msg_db: /home/roman.valls.guimera/transfer/transferred.db
program:
  olb: /usr/local/BclConverter-1.7.1/
  olb: /usr/local
algorithm:
  num_cores: 8
  ionice_class: 3
  nice: 15 
