msg_tag: sqn_finished_process
msg_store_tag: sqn_finished_store
msg_process_tag: sqn_finished_process

dump_directories:
  - /home/hiseq.hiseq/illumina
msg_db: /home/roman.valls.guimera/transfer/transferred.db
program:
  olb: /usr/local/BclConverter-1.7.1/
algorithm:
  num_cores: 7
  ionice_class: 3
  nice: 15 
