msg_tag: sqn_finished_process
msg_store_tag: sqn_finished_store 

dump_directories:
  - /home/hiseq.hiseq/illumina
msg_db: /home/roman.valls.guimera/transfer/transferred.db
program:
  olb: /usr/local/BclConverter-1.7.1/
algorithm:
  num_cores: 7
