msg_process_tag: sqn_finished_process
msg_store_tag: sqn_finished_store
dump_directories:
  - /home/hiseq.hiseq/illumina

# Pointer to a plain text file which will be used to keep track of
# directories that have already been transferred.
msg_db: /var/spool/nextgen/transferred.db
program:
# Offline basecaller, ex: CASAVA or OLB path
  olb: /usr/local/BclConverter-1.7.1/
algorithm:
  num_cores: 8
