msg_process_tag: sqn_finished_process
msg_store_tag: sqn_finished_store
dump_directories:
  - /array10
  - /array11
  - /array12
log_dir: /home/chapman/transfer/log
# Pointer to a plain text file which will be used to keep track of 
# directories that have already been transferred.
msg_db: /var/spool/nextgen/transferred.db
# Offline basecaller, ex: CASAVA or OLB path
program:
  olb: /home/chapman/install/OLB-1.8/OLB-1.8.0
  olb_make: make
algorithm:
  num_cores: 8
